//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleAppWithDapper.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Ultimate.
        /// </summary>
        public static string APP_Main_Title {
            get {
                return ResourceManager.GetString("APP_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Contacts_Grid_Created {
            get {
                return ResourceManager.GetString("Contacts_Grid_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Contacts_Grid_Email {
            get {
                return ResourceManager.GetString("Contacts_Grid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Contacts_Grid_FirstName {
            get {
                return ResourceManager.GetString("Contacts_Grid_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Contacts_Grid_Id {
            get {
                return ResourceManager.GetString("Contacts_Grid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Contacts_Grid_Modified {
            get {
                return ResourceManager.GetString("Contacts_Grid_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Contacts_Grid_SecondName {
            get {
                return ResourceManager.GetString("Contacts_Grid_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Contacts_Grid_Telephone {
            get {
                return ResourceManager.GetString("Contacts_Grid_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contact.
        /// </summary>
        public static string Contacts_Index_CreateNewRecord {
            get {
                return ResourceManager.GetString("Contacts_Index_CreateNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter search criteria....
        /// </summary>
        public static string Contacts_Index_EnterSearchCriteria_Placeholder {
            get {
                return ResourceManager.GetString("Contacts_Index_EnterSearchCriteria_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact app market disruptor number one..
        /// </summary>
        public static string Contacts_Index_Tagline {
            get {
                return ResourceManager.GetString("Contacts_Index_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts_Menu {
            get {
                return ResourceManager.GetString("Contacts_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string CreateContact_Back_Button {
            get {
                return ResourceManager.GetString("CreateContact_Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string CreateContact_Delete_Button {
            get {
                return ResourceManager.GetString("CreateContact_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string CreateContact_Edit_Button {
            get {
                return ResourceManager.GetString("CreateContact_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string CreateContact_Save_Button {
            get {
                return ResourceManager.GetString("CreateContact_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new contact.
        /// </summary>
        public static string CreateContact_Tagline {
            get {
                return ResourceManager.GetString("CreateContact_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New contact not created.
        /// </summary>
        public static string CreateContact_Toast_Failure {
            get {
                return ResourceManager.GetString("CreateContact_Toast_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New contact created.
        /// </summary>
        public static string CreateContact_Toast_Success {
            get {
                return ResourceManager.GetString("CreateContact_Toast_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string EditContact_Back_Button {
            get {
                return ResourceManager.GetString("EditContact_Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string EditContact_Delete_Button {
            get {
                return ResourceManager.GetString("EditContact_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EditContact_Edit_Button {
            get {
                return ResourceManager.GetString("EditContact_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the contact..
        /// </summary>
        public static string EditContact_Tagline {
            get {
                return ResourceManager.GetString("EditContact_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Menu {
            get {
                return ResourceManager.GetString("Home_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts, neatly organized.
        /// </summary>
        public static string LandingPage_Short_Description {
            get {
                return ResourceManager.GetString("LandingPage_Short_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one and only solution for any kind contact management..
        /// </summary>
        public static string LandingPage_Tagline {
            get {
                return ResourceManager.GetString("LandingPage_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACTS.
        /// </summary>
        public static string Layout_Contact_Navbar {
            get {
                return ResourceManager.GetString("Layout_Contact_Navbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Layout_Home_Navbar {
            get {
                return ResourceManager.GetString("Layout_Home_Navbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Layout_Login_Navbar {
            get {
                return ResourceManager.GetString("Layout_Login_Navbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string Layout_Register_Navbar {
            get {
                return ResourceManager.GetString("Layout_Register_Navbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform action. Please contact us..
        /// </summary>
        public static string Model_Error_Unable_To_Perform_Action {
            get {
                return ResourceManager.GetString("Model_Error_Unable_To_Perform_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact not updated.
        /// </summary>
        public static string UpdateContact_Toast_Failure {
            get {
                return ResourceManager.GetString("UpdateContact_Toast_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact updated.
        /// </summary>
        public static string UpdateContact_Toast_Success {
            get {
                return ResourceManager.GetString("UpdateContact_Toast_Success", resourceCulture);
            }
        }
    }
}
